services:
  master:
    image: cw_dbre:latest
    container_name: pg_master
    volumes:
      - pg_master-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DB_NODE_TYPE: "master"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
    ports:
      - 5434:5432
  replica1:
    image: cw_dbre:latest
    container_name: pg_replica
    volumes:
      - pg_replica1-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DB_NODE_TYPE: "replica"
    restart: unless-stopped
    ports:
      - 5433:5432
    depends_on:
      master:
        condition: service_healthy
volumes:
  pg_master-data:
    name: pg_master-data
  pg_replica1-data:
    name: pg_replica1-data
